# Generated by Django 3.0.4 on 2020-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
