# Generated by Django 3.0.4 on 2020-03-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200321_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='package',
            name='origination',
            field=models.CharField(default='00000 Blank Street 00000 CA', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='blank', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='blank', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='blank', max_length=20),
            preserve_default=False,
        ),
    ]
