# Generated by Django 3.0.4 on 2020-03-23 04:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200322_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='origination',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
