# Generated by Django 3.0.4 on 2020-03-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='package',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
