# Generated by Django 3.0.4 on 2020-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200324_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='origination',
            field=models.CharField(max_length=100),
        ),
    ]
