# Generated by Django 3.0.4 on 2020-03-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200324_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cost_of_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination_length',
            field=models.IntegerField(default=0),
        ),
    ]
