# Generated by Django 3.0.4 on 2020-03-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_profile_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Person'),
        ),
    ]
